### ISSUE TITLE
duplicated study arms?

### ISSUE THREAD

**Issue by HollieBirkinshaw** [softloud/happypillpain#20]
Working through the classifiers sheet for type, and a few studies have duplicated arms. Not sure if these are in your data or just somehow happened on the google sheet.

So far the studies I've noticed this on are:

- Grace 1985
- Sarziputtini 1998
- MacFarlane 1986
- Bird 2000

p.s. I emailed you about this first before remembering that we had git haha, so feel free to ignore that and we can just communicate here.

**Comment by softloud** [comment]
- [ ] check documentation for classifier generation
- [ ] write a target that counts how many studies and arms we have
- [ ] add target to data sheet
- [ ] link to this issue and document

Oh, and meanwhile, @holliebirkinshaw, I'm very much just learning the ropes with git. 

This is quite a sprawling project in a lot of ways, so I'm pushing myself (and you as well) to make use of issues for project management, 'cause we can tag issues, like how this possibly relates to #17, #11, #18. 

Ugh, grrl, I spent all day yesterday on a gantt chart system only to decide I am better off just sticking with a focussed list in my bullet journel. Refocussing today. 

Checking data top priority. Yes, thankyou! let's get our git on, time to level up my git project management.

**Comment by softloud** [comment]
Check this has been covered before closing #38
