### ISSUE TITLE
unique study identifier tag

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#21]
Hey @holliebirkinshaw,

I swear you said something about 14? but everything I'm running is stubbornly coming out at 128 out of 178 studies. 

I need to figure out if I have my numbers wrong, or if there's a bug in my code causing it not to update. Downloading latest covidence export now to see. 

\C

**Comment by HollieBirkinshaw** [comment]
Huh, we have 133 completed now through Covidence now.- 
![image](https://user-images.githubusercontent.com/79980803/111304277-75175800-864d-11eb-8abc-e899d58cba10.png)

**Comment by softloud** [comment]
Thanks for getting back to me. Okay, let's see how the export I just did 8 minutes ago comes out. 

Interesting! Thanks for getting back to me so quickly, you're a :star: :running_woman:

**Comment by HollieBirkinshaw** [comment]
Haha no worries, literally everything that i'm doing is at my laptop 😂

Plus if I don't do it when I get the notification I'm a bugger for forgetting! I'll be extracting throughout the day so the number complete will continue to go up as well

**Comment by softloud** [comment]
Moment of truth....

**Comment by softloud** [comment]
ach! nagdamnit! 
![image](https://user-images.githubusercontent.com/13408706/111304913-3df57680-864e-11eb-92bc-21f94939f2a6.png)

**Comment by softloud** [comment]
ach! nagdamnit! 
![image](https://user-images.githubusercontent.com/13408706/111304913-3df57680-864e-11eb-92bc-21f94939f2a6.png)

**Comment by HollieBirkinshaw** [comment]
Hmm. I'll complete a few more this afternoon and let you know when it says 135 and try again?

**Comment by softloud** [comment]
Cool. Ugh. And all those go through to export? 

Ugh. That means something isn't updating at my end. Might need to burn it down.

**Comment by HollieBirkinshaw** [comment]
not just you, I went into the excel sheet you exported an hour ago and removed the duplicates from the Study IDs. Left me with only 128 in the excel sheet.

![image](https://user-images.githubusercontent.com/79980803/111311233-de9b6480-8655-11eb-8494-b99a5d943cfb.png)

**Comment by softloud** [comment]
You are a freaking legend, my personal hero today.

**Comment by HollieBirkinshaw** [comment]
hey, do you remove duplicates? I realised I shouldn't just do that because there are some that have the same study ID assigned by Covidence even though they are different studies: 
![image](https://user-images.githubusercontent.com/79980803/111318090-a21f3700-865c-11eb-9a4b-f383a927d4d7.png)

**Comment by softloud** [comment]
Aha! So, `Study identifier` is not sufficient to identify the studies. What is the column called that the name is in?

**Comment by HollieBirkinshaw** [comment]
> What is the column called that the title is in?
that one is just Study Identifier, it's the very first column. 

> That is, what columns will allow me to uniquely identify the study?
The title of the study would, but it's not something we extract at the moment (Cochrane does for the individual study sheets but not for the .csv file typically). There's not a lot of identical study identifiers, so putting a/b/c after them once we have a final excel sheet is probably our best option.

**Comment by softloud** [comment]
Ah, so the export doesn't give the title, bummer. So is it relatively easy to change the study identifier value on the records? 

How did you get the column of titles? Where did you extract that from? Because I can create the unique study identfier by joining thata dataset to the covidence export.

**Comment by softloud** [comment]
:thinking: I wonder if I can extract it from the other file, there must be other fields that are the same.

**Comment by softloud** [comment]
aha, so here are four studies that all have more than one placebo. As in, they should be split into more than one study.

![image](https://user-images.githubusercontent.com/13408706/111812089-a8691980-88cf-11eb-9072-f8f52fedc1a8.png)


And not all studies included placebo. Also, the study random effect is not correct. Sigh. Downloading .csv version now to see if I can get the meta data.

**Comment by HollieBirkinshaw** [comment]
got a solution, there's a 'comments' box on the data extraction form that we have barely used, I'll add the titles in to that so then you'll be able to exclude based on duplicate comments in that column. I'll have it done by Monday, seems easier than trying to link files and it's also a permanent solution, once it's done it's done and it'll then always be on future downloads

**Comment by softloud** [comment]
- [ ] @HollieBirkinshaw add titles to`comments` column
- [ ] @softloud create proper study identifier using `study_identifier` and `comments`

**Comment by HollieBirkinshaw** [comment]
> @HollieBirkinshaw add titles to comments column

Done! 👍

**Comment by softloud** [comment]
This solved *so* many problems! Can't thank you enough. Looking forward to showing you just how much output solving this generated :tada:
