### ISSUE TITLE
install R and R Studio

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#24]
Hi @holliebirkinshaw,

I made you a flowchart of minimalistic tools that will give you way more access to the analysis. This is what we'll go through. In particular, before the meeting 

- [ ] install R
- [ ] install RStudio 

See flowchart for links.

It can be annoying so don't hesitate to shout out. It almost always means reading the boring documentation closely, which I can absolutely winggrrl.

**Comment by HollieBirkinshaw** [comment]
cool, installed both 🙃

**Comment by softloud** [comment]
You're a natural.
