### ISSUE TITLE
ranking of scales

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#31]
:thinking: @HollieBirkinshaw would it be as simple as ordering the [scale classifier googlesheet](https://docs.google.com/spreadsheets/d/1Q8QuZ9avto7TlBvHMpcPyX0NFI3R9nLevVjqBXDlHGg/edit#gid=1910672474) in rankings of scale, so if one scale is above another, for a given outcome, it is better. 

## :bulb: to try

- [x]  @HollieBirkinshaw orders sheet
-  @softloud refactors classifier with order of scale, order data by scale
- @softloud filters based on _first_ value of scale
- [ ] dependencies of scales in model levels

**Comment by softloud** [comment]
- [x] 0-10 nrs matching

**Comment by softloud** [comment]
- [x] 0_10_numerical_rating_scale

**Comment by softloud** [comment]
- [ ] pain_0_10_cm_vas_sf_mpq_baseline

Here's one for you, @HollieBirkinshaw 

Should this scale be mcgill or vas?

![image](https://user-images.githubusercontent.com/13408706/125488947-04dc51d1-46f1-4afe-b3e9-4e8769d634c0.png)

**Comment by HollieBirkinshaw** [comment]
> * [ ]  pain_0_10_cm_vas_sf_mpq_baseline
> 
> Here's one for you, @HollieBirkinshaw
> 
> Should this scale be mcgill or vas?
> 
> ![image](https://user-images.githubusercontent.com/13408706/125488947-04dc51d1-46f1-4afe-b3e9-4e8769d634c0.png)

VAS. The McGill questionnaire includes a 0-10 VAS, looks like this study has reported it separately.

**Comment by softloud** [comment]
merge with #54
