### ISSUE TITLE
Labelling outcomes/timepoints for mean change

### ISSUE THREAD

**Issue by HollieBirkinshaw** [softloud/happypillpain#33]
Not sure if we've addressed this (I can't remember what we've done honestly! 😂) but we might have to consider given how we've labelled things.

If the paper only reported mean change, then this was labelled as 'mean change from baseline [post-intervention]' or something similar. However, now I understand more about the coding of time points I wonder whether this could potentially be picked up as a baseline timepoint, which it isn't.

One solution might be for me to go into covidence and for any outcomes that report mean change, switch this to say 'mean change [post-intervention]' rather than 'mean change from baseline' to avoid to wrong labels. What do you think @softloud? It would only take me an hour or so but would solve all of this for any future downloads of data and save you a bunch of time troubleshooting etc.

**Comment by softloud** [comment]
Okay, let's see if I am understanding correctly. 

If it detects post intervention first, and doesn't check for baseline _if_ post intervention has been detected, then is that okay? 

In this snippet from the `wo_time` target, it execute in order. 

```
  # general labels
          str_detect(measure_desc, "follow_up") ~ "follow_up",
          stringr::str_detect(
            measure_desc,
            "end_of_treatment|post_treatment|post_intervention|endpoint|ednpoint"
          ) ~ "post_int",
          str_detect(measure_desc, "mid_intervention|within_trial") ~ "mid_int",
          str_detect(measure_desc, "baseline") ~ "baseline",
          TRUE ~ "unmatched"
        )
```

**Comment by softloud** [comment]
Hollie checked timepoints here. 

![image](https://user-images.githubusercontent.com/13408706/118806910-8d029680-b89f-11eb-87a3-5dce12efe87b.png)

**Comment by softloud** [comment]
Another check we did.

We checked endpoint and we checked post intervention.

Hollie is now satisfied that timepoints are labelling generally correctly. So. so happy. :)  

![image](https://user-images.githubusercontent.com/13408706/118807127-cf2bd800-b89f-11eb-9c2f-a0497dddc20e.png)
