### ISSUE TITLE
neuropathy comparison

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#44]
## objectives

Produce analysis on antidepressants for neuropathic pain for comparison with Andrew's work. 

## stuff to do

- [x] confirm with @HollieBirkinshaw that [this](https://www.sciencedirect.com/science/article/pii/S1474442214702510#tbl2) is the correct paper to compare with [nope, see below]
- [ ] split into long-form notes and summary page for site
- [ ] set long-form to eval=FALSE for pushing to site

***
### port to targets
- [ ] reproduction
- [ ] replication
- [ ] extensions

***
### replicate results
- [x] notes on which meta-analyses were performed
- [x] notes on exclusion criteria
- focus on amitriptyline and fibromyalgia
- outcomes: analgesic efficacy & adverse events
- [x] definition of alalgesic
- [x] update: got data! 

***
### reproduce analysis using our data for comparison

- [ ] get data 
- [ ] investigate multilevel modelling and model comparison using log-likelihood test
***
### extension
- [ ] nma
- [ ] nma on subgroup classes
- [ ] nma on amitriptilyne
- [ ] nma on everything

### eda

- [ ] how many have primary outcome pain?

## notes

- don't forget to convert log odds ratios to odds ratios

**Comment by HollieBirkinshaw** [comment]
https://www.cochranelibrary.com/cdsr/doi/10.1002/14651858.CD011824/full

Andrew's review analyses data in three tiers of quality, it's under the data synthesis section :)

**Comment by HollieBirkinshaw** [comment]
p.s. not sure if this makes sense to you but this is how they calculated NNT:

'We calculated numbers needed to treat to benefit (NNTs) as the reciprocal of the absolute risk reduction (ARR) (McQuay 1998).'

**Comment by HollieBirkinshaw** [comment]
Have extracted the data from the same studies that Andrew included in his amitriptyline and fibromyalgia review. Have uploaded to shared onedrive folder 👍
