### ISSUE TITLE
Actions from team meeting

### ISSUE THREAD

**Issue by HollieBirkinshaw** [softloud/happypillpain#47]
Hey, these are the actions for you/the analysis I picked up on from the team meeting. Hope they make sense to you (I understand the first 3 and then I'm a bit lost 🙈)

- [ ] N/Sample size for each arm/comparison in the plots
- [ ] Forest plots: make dots bigger/smaller dependent on sample size to allow the team to see which trials/comparisons have the most participants
- [ ] Display heterogeneity in plots
- [ ] Examine whether drug class explains any of the heterogeneity in the results
- [ ] Pairwise comparisons to be able to examine discrepancies

**Comment by softloud** [comment]
You are the best! Thank you :hugs:

**Comment by softloud** [comment]
make sure these items are completed before closing #52
