### ISSUE TITLE
study labels

### ISSUE THREAD

**Issue by softloud** [softloud/happypillpain#53]
- moderate pain
- sleep 

Some titles in extractions don't match titles in Covidence.

- [x] @HollieBirkinshaw has a look and sees what can be fixed
- [x] @softloud check to see what still doesn't match
- [x] implement p 9 pipeline
- [x] keep covidence title and label for comparison prefix with `covidence_`
- [x] debug no matches
- [x] @softloud check again

**Comment by HollieBirkinshaw** [comment]
Re-uploaded moderate pain and sleep with the titles corrected 👍

**Comment by softloud** [comment]
w00t all the studies are labelled now!

**Comment by softloud** [comment]
- [ ] make sure this is documented in #38 documentation
